export const SET_PAGE_DATA = 'SET PAGE DATA';
export const UPDATE_BOOK = 'UPDATE_BOOK';
export const KEYBOARD_WILL_SHOW = 'KEYBOARD_WILL_SHOW';
export const KEYBOARD_WILL_HIDE = 'KEYBOARD_WILL_HIDE';
export const INPUT_FOCUSED = 'INPUT_FOCUSED';
export const INPUT_SWIPE_STARTED = 'SWIPE START';
export const INPUT_SWIPE_ENDED = 'SWIPE END';
export const ON_VERTICAL_SCROLL = 'ON VERTICAL SCROLL';

